export const formAdressData = {
  gender: [
    { value: "", type: "請選擇稱謂" },
    { value: "mr", type: "先生" },
    { value: "ms", type: "女士" },
    { value: "none", type: "不顯示" },
  ],

  city: [
    { value: "", name: "請選擇縣市" },
    { value: "KLU", name: "基隆市" },
    { value: "TPH", name: "新北市" },
    { value: "TPE", name: "台北市" },
    { value: "TYC", name: "桃園市" },
    { value: "HSH", name: "新竹縣" },
    { value: "HSC", name: "新竹市" },
    { value: "MAC", name: "苗栗市" },
    { value: "MAL", name: "苗栗縣" },
    { value: "TXG", name: "台中市" },
    { value: "CWH", name: "彰化縣" },
    { value: "CWS", name: "彰化市" },
    { value: "NTC", name: "南投市" },
    { value: "NTO", name: "南投縣" },
    { value: "YLH", name: "雲林縣" },
    { value: "CHY", name: "嘉義縣" },
    { value: "CYI", name: "嘉義市" },
    { value: "TNN", name: "台南市" },
    { value: "KHH", name: "高雄市" },
    { value: "IUH", name: "屏東縣" },
    { value: "PTS", name: "屏東市" },
    { value: "ILN", name: "宜蘭縣" },
    { value: "ILC", name: "宜蘭市" },
    { value: "HWA", name: "花蓮縣" },
    { value: "HWC", name: "花蓮市" },
    { value: "TTC", name: "台東市" },
    { value: "TTT", name: "台東縣" },
    { value: "PEH", name: "澎湖縣" },
    { value: "GNI", name: "綠島" },
    { value: "KYD", name: "蘭嶼" },
    { value: "KMN", name: "金門縣" },
    { value: "MZW", name: "馬祖" },
    { value: "LNN", name: "連江縣" },
  ],
};
